# To learn about this file, please see https://www.gitpod.io/docs/references/gitpod-yml

image: gitpod/workspace-postgres

tasks:
  - init: yarn install
    command: yarn rw prisma migrate dev && yarn rw dev --fwd="--allowed-hosts all --open=false"
    env:
      DATABASE_URL: "file:./dev.db"
      PRISMA_HIDE_UPDATE_MESSAGE: true

ports:
  - port: 5432
    name: DB
    onOpen: ignore
  - port: 8910
    name: RedwoodJS web application
    onOpen: open-preview
  - port: 8911
    name: RedwoodJS api application
    onOpen: ignore

vscode:
  extensions:
    - "dbaeumer.vscode-eslint"
    - "eamodio.gitlens"
    - "mgmcdermott.vscode-language-babel"
    - "wix.vscode-import-cost"
    - "pflannery.vscode-versionlens"
    - "editorconfig.editorconfig"
    - "prisma.prisma"
    - "graphql.vscode-graphql"
